---
title: "Mastering AI Chatbots: Optimizing Research through Effective Use"
subtitle: "Skill training LBG Career Center"
author: "Hannah Metzler & Konstantin Hebenstreit <br> Slides: https://github.com/hannahmetzler/ai_skills"
date: "October 29 2024"
format: 
  revealjs: 
    transition: "slide"
    theme: [default, custom.scss]
    incremental: false
    aspect-ratio: 16:9
    slide-number: true
    title-slide: true  # This enables the title slide
    speakerNotes: true
editor: source
---

## Who are we?

### Dr. Hannah Metzler

Complexity Science Hub & Meduni Vienna <br> Psychology, Neuroscience & Data Science <br> https://hannahmetzler.eu \| metzler\@csh.ac.at <br> X: [\@hannahmetzler1](https://x.com/hannahmetzler1)

### Konstanstin Hebenstreit, M.Sc.

Artificial Intelligence Institute at Meduni Vienna <br> Artificial Intelligence, LLMs & Data Science <br> konstantin.hebenstreit\@meduniwien.ac.at <br> X: [\@K_Hebenstreit](https://x.com/K_Hebenstreit)

## Who are you?

-   Scientific discipline & topic area
-   One thing you have already used LLMs for
-   If any: particular expectation or interests for today

## (Rough) plan for the day {.smaller}

|               |                                |
|---------------|--------------------------------|
| 9h30 -  10h15   | Introduction to LLMs|
| 10h15 - 11h00   | Chatbot essentials  |
|  | **Coffee break** |
| 11h15 -  11h50   | Prompting strategies  |
| 11h50 -  12h30   | Chatbots in research: Writing |
| | **Lunch break** |
| 13h30 - 14h15 | Customizing Chatbots  |
| 14h15 - 15h00   | Scientific tools based on LLMs |
|  | **Coffee break** |
| 15h15 - 15h30   | Other researcher use cases |
| 15h30 - 16h00  | Ethical considerations  |
| 16h00 - 16h30    | Try something new or fun |
| 16h30 - 17h | Resources, Questions, Closing round |

## Access to LLM chatbots for today

- Who has a paid account?
- Did all others create a Gemini pro trial account?
-   Log in for 8 more accounts

# Introduction to LLMs

[Slides](https://hannahmetzler.eu/ai_skills/Introduction/)
