---
title: "Enhancing your research outputs with LLM Chatbots"
subtitle: "Mastering AI Chatbots: Optimizing Research through Effective Use"
author: "Hannah Metzler & Konstantin Hebenstreit <br> Slides: https://github.com/hannahmetzler/AI_skills"
date: "October 29 2024"
format: 
  revealjs: 
    transition: "slide"
    theme: [default, custom.scss]
    incremental: false
    aspect-ratio: 16:9
    slide-number: true
    title-slide: true  # This enables the title slide
    speakerNotes: true
editor: source
---

# Scientific tools based on LLMs

## Overview

## Perplexity (5 min)
- [**Perplexity AI**](https://www.perplexity.ai/)
- Like search engine, scientific references
    -   [Example testosterone & behaviour](https://www.perplexity.ai/search/what-are-the-2WzaWWlKRm.4ge6IDNvx3w)
- Exploration
- Tip: Search for best tools using the "social" option, as reddit is searched. (Less clutter/ads)

## Elicit (5 min)
Link:   [**Elicit AI**](https://elicit.com/): Analyse research papers at superhuman speed
    -   Slides [here](https://hannahmetzler.eu/digital_tools_research/04_literature/index.html#7)
    -   [Beispiel](https://elicit.com/notebook/842fc893-e8f5-49a9-8bfb-d2ec6d1831fb)
    
## Exercise Elicit or Perplexity (10 min)

-   Exploring a completely new topic
    
## NotebookLM (10 min)
Link:   [NotebookLM](https://notebooklm.google.com/): Document-based analyses [Example Tutorial](https://www.gaiforresearch.com/post/introducing-notebooklm-your-ai-powered-research-assistant) [Paper](https://www.nature.com/articles/s41586-024-07417-w)


## Other tools to explore

- [Tome]() for presentations
-   Translation [www.deepl.com](www.deepl.com)
- ResearchRabbit for Literature search based on paper networks

## Exercise (15 min)



# Researcher use cases

## Summarizing content

-   Record workshops, interviews, discussions: note taking and summarization
-   Upload long reports/papers, have them analysed e.g. compare 2 university annual reports, create a table of differences
-   Summarise long documents: Upload link or file
    - Long newspaper articles: listen as a podcast (Notebook LM)
    - Grant writing instructions, specific questions
    - Journal requirements
-   Summarizing a paper based on [Zotero note example](https://chatgpt.com/share/67166160-4cdc-800b-8965-487a32301be8)
    
## Structuring stuff

- Suggest outline/structure for a presentation
- Course Syllabi

## Getting feedback on everything
-   Upload presentation slides


## Area specific research tasks

-   Surveys, e.g. [develop & test MC questions](https://chatgpt.com/share/67166062-c0e4-800b-b018-07562fc3819d), [check comprehensibility](https://chatgpt.com/share/6716608a-2044-800b-9461-c7508b2912b4), [answer options](https://chatgpt.com/share/67166a29-9330-800b-b041-41c1b9554e8c)
-   Statistics questions [Example](https://chatgpt.com/share/670fd64f-cd54-800b-8539-84730cb2414c)
-   Discussion about [social media & mental health](https://chatgpt.com/share/671668f9-c280-800b-83ef-0e591c1200ca)

::: notes
survey item to be updated, new conversation with chatgpt necessary
:::


## Prompts for...

::: columns
::: column
- Idea generation
- Structuring content
- Proofreading
- Citation guidance
- Paraphrasing
- Improving language & vocabulary
:::
::: column
- Clarifying concepts
- Draft review
- writing prompts
- Abstract & Summary
- Help with Methods
:::
::::

<https://learnprompt.org/chatgpt-prompts-for-academic-writing/>

<!-- ## Brainstorming & Exploration -->

<!-- -   [Journalist interview questions](https://chatgpt.com/share/67166aa4-64e4-800b-b1fc-f5099ce4c53f) -->
<!-- -   [Application: Future research directions](https://chatgpt.com/share/67166bc6-8c38-800b-81c7-abc648c1cbea) (second half of chat) -->
<!--     -   What does research on why people donate show? Please include research from Lucius Caviola, Stefan Schubert, and their collaborators. -->
<!--     -   Have any interventions to increase donations, or get more people to donate, emerged from this research? -->
<!--     -   What are the most important open questions in psychology regarding how to foster prosocial behavior and cooperation? -->
<!--     -   What is a concrete experiment that you would do to investigate prosocial behavior, for example donations? Which design, which experimental groups, or which psychological measures would you use? -->

<!-- ## Exercise Summarizing: (15 minutes) {.smaller visibility='hidden'} -->

<!-- ### Extract relevant points from long content  -->

<!-- - Choose a recent workshop/lecture, meeting you attended or paper you read -->
<!--   - You have some written record (notes, slides, transcript) -->
<!-- - Copy/paste or upload the document -->
<!-- - Define the persona: academic assistant organizing meeting notes, PhD student preparing for exam, researcher who writes a meta-analysis -->
<!-- - Define the audience: you, other researchers -->
<!-- - Context about workshop/lecture/meeting/paper  -->
<!-- - Task: Summarize key points that are relevant for you: "Summarize the main points in bullet points with a focus on To Dos/study design/what could be asked in the exam" -->
<!-- - Add examples if you have any (points that are relevant, exam questions,...) -->

