---
title: "Mastering AI Chatbots: Optimizing Research through Effective Use"
subtitle: "Skills training LBG Career Center"
author: "Hannah Metzler & Konstantin Hebenstreit <br> Slides: https://github.com/hannahmetzler/ai_skills"
date: "April 29 2025"
format: 
  revealjs: 
    transition: "slide"
    theme: [default, custom.scss]
    incremental: false
    aspect-ratio: 16:9
    slide-number: true
    title-slide: true  # This enables the title slide
    speakerNotes: true
editor: source
---

## Who are we?

### Dr. Hannah Metzler

Complexity Science Hub <br> Psychology, Neuroscience & Data Science <br> https://hannahmetzler.eu \| metzler\@csh.ac.at <br>
 <br>

### Konstanstin Hebenstreit, M.Sc.

Artificial Intelligence Institute at Meduni Vienna <br> Artificial Intelligence, LLMs & Data Science <br> konstantin.hebenstreit\@meduniwien.ac.at <br> 

## Who are you?

- Scientific discipline & topic area
- Which problems do you encounter when using LLMs? 
- What works well?
- If any: particular expectation or interests for today

## (Rough) plan for the day {.smaller}

|               |                                |
|---------------|--------------------------------|
| 9h00 - 9h30    | Welcome, setup & short introduction |
| 9h30 - 10h30   | Introduction to LLMs |
| 10h30 - 11h00  | Ethical Considerations |
|               | **Coffee break**              |
| 11h15 - 12h30  | Chatbot Essentials |
|               | **Lunch break**               |
| 13h30 - 14h15  | Advanced Prompting |
| 14h15 - 15h00  | Deep Research Mode |
|               | **Coffee break**              |
| 15h15 - 16h00  | Customizing Chatbots |
| 16h00 - 16h45  | Scientific tools based on LLMs |
| 16h45 - 17h00  | Resource Sharing & Open Questions & Feedback |


## Slides for today {.smaller}

- [Introduction to LLMs](https://hannahmetzler.eu/ai_skills/IntroEthicsShort/)
- [Ethics](https://hannahmetzler.eu/ai_skills/IntroEthicsShort/#/important-ethical-aspects)
- [Chatbot essentials](https://hannahmetzler.eu/ai_skills/Prompting)
- [Advanced prompting strategies](https://hannahmetzler.eu/ai_skills/Prompting/#/advanced-prompting-strategies)
- [Deep Research Mode](https://hannahmetzler.eu/ai_skills/DeepResearch)
- [Customizing Chatbots](https://hannahmetzler.eu/ai_skills/Customizing)
- [Scientific tools based on LLMs](https://hannahmetzler.eu/ai_skills/Tools)
- [Collection of use cases](https://hannahmetzler.eu/ai_skills/UseCases)
- [Resources](https://hannahmetzler.eu/ai_skills/Resources)

## Access to LLM chatbots for today

- Did you all create a Gemini pro trial account?
- Do you have accounts on ChatGPT and Claude? (or Gmail account details to log in)

# Introduction to LLMs

[Slides](https://hannahmetzler.eu/ai_skills/IntroEthicsShort/)
